#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Olivia Cattau's lab notebook

# Your name to show in the footer
author: Olivia Cattau

# Short bio or description (displayed in the header)
description: Steven Roberts' Lab UW

# List of links in the navigation bar
navbar-links:
  CV: "cv/Cattau_CV_July_2021.pdf"
  About: "aboutme"
  Lab Notebook: "notebook"
  Resources:
    - Markdown Cheat Sheet: "https://www.markdownguide.org/cheat-sheet/"
    - Roberts Lab handbook: "https://robertslab.github.io/resources/"
    - Beautiful Jekyll: "https://beautifuljekyll.com"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://pacifichybreed.com/wp-content/uploads/2019/11/olivia-1-300x300.jpg 



# Includes an icon in the footer for each username you enter
footer-links:
  #dribbble:
  email: ocattau@uw.edu
  #facebook:
  #flickr:
  github: ocattau
  instagram: olivia_cattau
  #linkedin:
  #pinterest:
  #rss: # just type anything here for a working RSS icon
  #twitter: 
  #stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  #youtube: # channel/<your_long_string> or user/<user-name>
  #googleplus: # anything in your profile username that comes after plus.google.com/
  
# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
  
# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "ocattau.github.io"

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# Suggest a colour for mobile browsers to use as the browser's theme. This is only supported by a few mobile browsers.
#mobile-theme-col: "#0085A1"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 150

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: ocattau
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://ocattau.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"
      show-avatar: true
      
# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  
# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

